[platformio]
default_envs = seeed_xiao_esp32s3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
framework = arduino
build_type = release
upload_protocol = esptool
monitor_speed = 115200 
monitor_filters = 
	default
	esp32_exception_decoder
; lib_ldf_mode = deep
; board_build.filesystem = littlefs
lib_deps =
;    SPI
;    Wire
;	https://github.com/FastLED/FastLED.git
;   FastLED
	lib/FastLED ; currently based on e229673 (a8b45ad for P4-WIFI6)
	bblanchon/ArduinoJson @ ^7.4.2
build_flags =
;   -DDEBUG
;	-DFASTLED_DEBUG=1
;	-DFASTLED_LOG_RMT_ENABLED=0
    -DCORE_DEBUG_LEVEL=0
    -DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
	-DARDUINO_USB_CDC_ON_BOOT=1
;	-DARDUINO_USB_MODE=0 ; Serial is native USB CDC (TinyUSB).
	-DARDUINO_USB_MODE=1 ;→ Serial is USB Serial/JTAG (hardware CDC).

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3
board_build.flash_mode = qio
# Removed huge_app.csv - it prevented OTA and erased LittleFS on every upload
# Default partition scheme preserves filesystem during updates
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_ESP_SYSTEM_MEMPROT_FEATURE=0
debug_tool = esp-builtin
debug_server =
	$PLATFORMIO_CORE_DIR/packages/tool-openocd-esp32/bin/openocd
	-f
	$PROJECT_DIR/openocd_debug.cfg
debug_port = localhost:3333
debug_init_cmds =
	target extended-remote $DEBUG_PORT
	set remote hardware-watchpoint-limit 2
	set remote hardware-breakpoint-limit 2
	set remotetimeout 20
	monitor reset halt
	$LOAD_CMDS
	thbreak app_main
	continue

[env:esp32-p4]
board = esp32-p4-evboard
framework = arduino, espidf
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
check_skip_packages = yes
custom_component_remove = espressif/esp_modem
                          espressif/esp-dsp
                          espressif/network_provisioning
                          espressif/esp-zboss-lib
                          espressif/esp-zigbee-lib
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/qrcode
                          espressif/esp-sr
                          espressif/libsodium
                          espressif/esp-modbus
                          chmorgan/esp-libhelix-mp3
                          espressif/esp32-camera
lib_ignore =              BLE
                          BluetoothSerial
                          SimpleBLE
                          WiFiProv
                          ArduinoOTA
build_flags = 
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DFASTLED_DISABLE_DBG=0
    -DFASTLED_LOG_RMT_ENABLED=1
    -DFASTLED_LOG_PARLIO_ENABLED=1
;	-DCONFIG_NIMBLE_CPP_IDF=1
