#pragma once
#include <stdint.h>

enum Emitter : uint8_t {
    EMITTER_ORBITALDOTS = 0,
    EMITTER_SWARMINGDOTS,
    EMITTER_LISSAJOUS,
    EMITTER_BORDERRECT,
    EMITTER_AUDIODOTS,
    EMITTER_NOISEKALEIDO,
    EMITTER_CUBE,
    // future: EMITTER_TRIANGLE, ...
    EMITTER_COUNT
};

enum Flow : uint8_t {
    FLOW_NOISE = 0,
    FLOW_FROMCENTER,
    FLOW_DIRECTIONAL,
    FLOW_RINGS,
    FLOW_SPIRAL,
    // future: FLOW_TOCENTER, FLOW_POLARWARP, ...
    FLOW_COUNT
};
