#pragma once
#include <stdint.h>

enum Emitter : uint8_t {
    EMITTER_ORBITALDOTS = 0,
    EMITTER_SWARMINGDOTS,
    EMITTER_AUDIODOTS,
    EMITTER_LISSAJOUS,
    EMITTER_BORDERRECT,
    EMITTER_NOISEKALEIDO,
    EMITTER_CUBE,
    EMITTER_FLUIDJET,
    EMITTER_COUNT
};

enum Flow : uint8_t {
    FLOW_NOISE = 0,
    FLOW_RADIAL,
    FLOW_DIRECTIONAL,
    FLOW_RINGS,
    FLOW_SPIRAL,
    FLOW_FLUID,
    FLOW_COUNT
};
